### ISSUE TITLE
Error running demo

### ISSUE THREAD

**Issue by TelegramSam** [IDunion/OpenIDIDComm#3]
Running the client as described in the readme returns the following error:

```
\Client>npx tsx ./clientDidToken.ts

<large dump of info>

TypeError: Cannot read properties of undefined (reading 'kid')
    at <anonymous> (c:\Users\teleg\Documents\repos\OpenIDIDComm\Code\Client\clientDidToken.ts:37:105)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

Node.js v18.18.0
```

The issuer does work.

Any ideas?

**Comment by void1042** [comment]
Maybe veramo for some reason created a new did internally, which would use the same did but a different key, resulting in a mapping failure. We hoped it would just seamlessly use the existing did in `database.sqlite`.

Could you maybe `console.log(identifier.keys)` after it's created in line 25 and paste the output? This info could also be gathered by using the Veramo CLI (https://veramo.io/docs/veramo_agent/cli_tool), but it's not supported on Windows yet.

**Comment by TelegramSam** [comment]
```js
{
  did: 'did:web:raw.githubusercontent.com:IDunion:OpenIDIDComm:main:DID_Documents:Client',
  controllerKeyId: '9f67998c5845f39e07fd5819f8948fe5944fdcc6e76a5f3d1be3e58d1e3bf4d6',
  provider: 'did:web',
  services: [
    {
      id: '123',
      type: 'DIDCommMessaging',
      serviceEndpoint: 'http://localhost:8081/didcomm',
      description: null
    }
  ],
  keys: [
    {
      kid: '9f67998c5845f39e07fd5819f8948fe5944fdcc6e76a5f3d1be3e58d1e3bf4d6',
      type: 'Ed25519',
      kms: 'local',
      publicKeyHex: '9f67998c5845f39e07fd5819f8948fe5944fdcc6e76a5f3d1be3e58d1e3bf4d6',
      meta: [Object]
    }
  ],
  alias: 'raw.githubusercontent.com:IDunion:OpenIDIDComm:main:DID_Documents:Client'
}
```

**Comment by TelegramSam** [comment]
@void1042 I'm anxious to get this working before the weekend so I'm prepped for IIW next week. Can you reach out on Discord (_telegramsam) and we can set up a time for demo debugging?

**Comment by void1042** [comment]
Solution was to run Client from inside "Code/" instead of "Code/Client", because in the latter the existing database isn't found
